### ISSUE TITLE
License suggestion

### ISSUE THREAD

**Issue by planemad** [prasannar2009/chennaitransitmap#1]
Hi @prasannar2009 , amazing work on the map. Hope you are aware that it is use on Wikipedia after someone uploaded the pdf under a CC-0 license which looks incorrect https://commons.wikimedia.org/wiki/File:Chennai_transit_map_future_v1-0.pdf

The map clearly says CC-BY-NC (no commercial use) which would make it unsuitable for use on Wikipedia which will at least require CC-BY-SA which allows commercial use.

Can I suggest you clarify the license so we can fix the usage on Wikipedia. If you would like to stick with CC-BY-NC, it would need to be deleted from [several Wikipedia articles](https://commons.wikimedia.org/wiki/File:Chennai_transit_map_future_v1-0.pdf#globalusage).

**Comment by prasannar2009** [comment]
Hi @planemad, Thanks for the heads up and suggestion! I have changed the licence now. I did upload the new pdf on https://commons.wikimedia.org/wiki/File:Chennai_transit_map_future_v1-0.pdf , but I guess it needs to be deleted and re-uploaded as a new file, because the licence has changed?

**Comment by planemad** [comment]
@prasannar2009 , thank you, have updated the license on the same page to CC-by-4.0 . 

As an aside, the file was marked for deletion since it was confused as a fantasy map, [have made clarifications](https://commons.wikimedia.org/wiki/Commons:Deletion_requests/File:Chennai_transit_map_future_v1-0.pdf) so that it's not deleted.
